CREATE TABLE Users(
    Username VARCHAR(255) PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Privilege SMALLINT NOT NULL
);

CREATE TABLE Sessions(
    SessionID VARCHAR(128) PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Time INT NOT NULL
);

CREATE TABLE Categories(
    CategoryID CHAR(32) PRIMARY KEY,
    Name VARCHAR(64) NOT NULL,
    Description TEXT NOT NULL
);

CREATE TABLE Tasks(
    TaskID CHAR(32) PRIMARY KEY,
    CategoryID CHAR(32),
    CreatorName VARCHAR(255),
    Title VARCHAR(64) NOT NULL,
    Description TEXT NOT NULL,
    StartDate DATE NOT NULL,
    Status SMALLINT NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON DELETE SET NULL,
    FOREIGN KEY (CreatorName) REFERENCES Users(Username) ON DELETE SET NULL
);

CREATE TABLE Assignees(
    TaskID CHAR(32) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    PRIMARY KEY (TaskID, Username),
    FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID) ON DELETE CASCADE,
    FOREIGN KEY (Username) REFERENCES Users(Username) ON DELETE CASCADE
);

CREATE TABLE Updates(
    Type SMALLINT PRIMARY KEY,
    Time INT NOT NULL,
    Data TEXT
);
