CREATE TABLE Users(
    Username VARCHAR(255) PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Privilege TINYINT(8) NOT NULL
);

CREATE TABLE Sessions(
    SessionID VARCHAR(128) PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Time INT(32) NOT NULL
);
